module.exports = {
	INCREMENT: "INCREMENT",
	DECREMENT: "DECREMENT",
	GET_PRODUCTS: "GET_PRODUCTS",
	DELETE_PRODUCT: "DELETE_PRODUCT",
	GET_PRODUCT: "GET_PRODUCT",
	SAVE_PRODUCT: "SAVE_PRODUCT",
	START_LOADING: "START_LOADING",
	END_LOADING: "END_LOADING"
}
